import { create } from "zustand";
import { devtools } from "zustand/middleware";

export interface Book {
  id: number;
  title: string;
  author: string;
  rating?: 1 | 2 | 3 | 4 | 5;
  tags?: JSX.Element[];
  review?: string;
  related?: number[]; // ids

  url: string;
  fallbackBackgroundColor: string;
  fallbackTextColor: string;
  isbn: string;
  status: "have-read" | "currently-reading" | "will-read" | "wanna-buy";
}

function t(...tags: string[]): JSX.Element[] {
  return tags as unknown as JSX.Element[];
}

export const BOOKS: Book[] = [
  {
    id: 1,
    title: "Das Café am Rande der Welt",
    author: "John Strelecky",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#2c3e6b",
    fallbackTextColor: "#dde9fa",
    isbn: "9783423209694",
    url: "",
    related: [2, 3, 4, 7],
  },
  {
    id: 2,
    title: "Wiedersehen im Café am Rande der Welt",
    author: "John Strelecky",
    rating: 4,
    status: "have-read",
    fallbackBackgroundColor: "#253558",
    fallbackTextColor: "#d4e6f8",
    isbn: "9783423348966",
    url: "",
    related: [1, 3, 4, 7],
  },
  {
    id: 3,
    title: "Auszeit im Café am Rande der Welt",
    author: "John Strelecky",
    rating: 4,
    status: "have-read",
    fallbackBackgroundColor: "#1e2d4d",
    fallbackTextColor: "#cde0f5",
    isbn: "3423349646",
    url: "",
    related: [1, 2, 4, 7],
  },
  {
    id: 4,
    title: "The Big Five",
    author: "John Strelecky",
    rating: 4,
    status: "have-read",
    fallbackBackgroundColor: "#304570",
    fallbackTextColor: "#e0ecff",
    isbn: "9783423345286",
    url: "",
    related: [1, 2, 3, 7],
  },
  {
    id: 5,
    title: "Kaffee und Zigaretten",
    author: "Ferdinand von Schirach",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#2a2520",
    fallbackTextColor: "#f5e6c8",
    isbn: "9783630876108",
    url: "",
  },
  {
    id: 6,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    rating: 3,
    status: "have-read",
    fallbackBackgroundColor: "#163d2b",
    fallbackTextColor: "#c8f0d8",
    isbn: "1612681131",
    url: "",
  },
  {
    id: 7,
    title: "Safari des Lebens",
    author: "John Strelecky",
    rating: 4,
    status: "have-read",
    fallbackBackgroundColor: "#4a3a18",
    fallbackTextColor: "#f8f0c8",
    isbn: "3423345861",
    url: "",
    related: [1, 2, 3, 4],
  },
  {
    id: 8,
    title: "Der Konfuzianismus",
    author: "Volker Zotz",
    rating: 3,
    status: "have-read",
    fallbackBackgroundColor: "#7a3500",
    fallbackTextColor: "#fff0cc",
    isbn: "3737409757",
    url: "",
  },
  {
    id: 9,
    title: "Erleuchtung finden in einer lauten Welt",
    author: "Jack Kornfield",
    rating: 3,
    status: "have-read",
    fallbackBackgroundColor: "#8c4200",
    fallbackTextColor: "#fff5d8",
    isbn: "344234123X",
    url: "",
  },
  {
    id: 10,
    title: "Dienstags bei Morrie",
    author: "Mitch Albom",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#1c2e40",
    fallbackTextColor: "#d0e8f8",
    isbn: "3442487226",
    url: "",
  },
  {
    id: 11,
    title: "101 Essays that will change the way you think",
    author: "Brienna West",
    rating: 4,
    status: "have-read",
    fallbackBackgroundColor: "#3d2845",
    fallbackTextColor: "#f0e0f8",
    isbn: "9781804221747",
    url: "",
  },
  {
    id: 12,
    title: "Der kleine Taschenphilosoph",
    author: "Brigitte Hellmann",
    rating: 3,
    status: "have-read",
    fallbackBackgroundColor: "#2a2d42",
    fallbackTextColor: "#d8daf0",
    isbn: "3423340991",
    url: "",
  },
  {
    id: 13,
    title: "4321",
    author: "Paul Auster",
    status: "will-read",
    fallbackBackgroundColor: "#4a2070",
    fallbackTextColor: "#ede7f6",
    isbn: "9783498000974",
    url: "",
  },
  {
    id: 14,
    title: "Schnelles Denken, langsames Denken",
    author: "Daniel Kahneman",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#1a3d4a",
    fallbackTextColor: "#c0dde8",
    isbn: "3886808866",
    url: "",
  },
  {
    id: 15,
    title: "Man's Search for Meaning",
    author: "Viktor Frankl",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#4a3010",
    fallbackTextColor: "#f5e8c8",
    isbn: "9780807014295",
    url: "",
  },
  {
    id: 16,
    title: "The Monk Who Sold His Ferrari",
    author: "Robin Sharma",
    rating: 4,
    status: "have-read",
    fallbackBackgroundColor: "#9c4a00",
    fallbackTextColor: "#ffe8c0",
    isbn: "0007848420",
    url: "",
  },
  {
    id: 17,
    title: "Die Liebe",
    author: "Peter Lauster",
    rating: 4,
    status: "have-read",
    fallbackBackgroundColor: "#6e0f35",
    fallbackTextColor: "#ffd6e8",
    isbn: "3499176777",
    url: "",
  },
  {
    id: 18,
    title: "The Mind Is Flat",
    author: "Nick Chater",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#EFEAE3",
    fallbackTextColor: "#212121",
    isbn: "0241208777",
    url: "",
  },
  {
    id: 19,
    title: "Life Is Short and So Is This Book",
    author: "Peter Atkins",
    rating: 4,
    status: "have-read",
    fallbackBackgroundColor: "#FFEA53",
    fallbackTextColor: "#212121",
    isbn: "0615467350",
    url: "",
  },
  {
    id: 20,
    title: "Atomic Habits",
    author: "James Clear",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#014c7a",
    fallbackTextColor: "#c0e0f8",
    isbn: "0735211299",
    url: "",
  },
  {
    id: 21,
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    rating: 3,
    status: "have-read",
    fallbackBackgroundColor: "#1a3020",
    fallbackTextColor: "#c0e8d0",
    isbn: "9780449214923",
    url: "",
  },
  {
    id: 22,
    title: "Über die Psychologie des Geldes",
    author: "Morgan Housel",
    rating: 3,
    status: "have-read",
    fallbackBackgroundColor: "#1e4530",
    fallbackTextColor: "#cceedd",
    isbn: "",
    url: "",
  },
  {
    id: 23,
    title: "Dinge geregelt kriegen ohne einen Funken Selbstdisziplin",
    author: "Kathrin Passig, Sascha Lobo",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#384080",
    fallbackTextColor: "#d8e0ff",
    isbn: "9783499007316",
    url: "",
  },
  {
    id: 24,
    title: "Patriarchale Belastungsstörung",
    author: "Beatrice Frasl",
    rating: 4,
    status: "have-read",
    fallbackBackgroundColor: "#FFA400",
    fallbackTextColor: "#212121",
    isbn: "3709981751",
    url: "",
  },
  {
    id: 25,
    title: "The Good Enough Parent",
    author: "The School of Life",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#7a3000",
    fallbackTextColor: "#ffe8cc",
    isbn: "1912891549",
    url: "",
    related: [28, 35, 43],
  },
  {
    id: 26,
    title: "Die philosophische Hintertreppe",
    author: "Wilhelm Weischedel",
    rating: 3,
    status: "currently-reading",
    fallbackBackgroundColor: "#353050",
    fallbackTextColor: "#d5d0f0",
    isbn: "",
    url: "",
    related: [],
  },
  {
    id: 27,
    title: "Factfulness",
    author: "Hans Rosling",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#1a3558",
    fallbackTextColor: "#c8daef",
    isbn: "9781250107817",
    url: "",
  },
  {
    id: 28,
    title: "Relationships",
    author: "The School of Life",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#5c1428",
    fallbackTextColor: "#ffd0dc",
    isbn: "",
    url: "",
    related: [25, 35, 43],
  },
  {
    id: 29,
    title: "Das Wunder der Wertschätzung",
    author: "Reinhard Haller",
    rating: 3,
    status: "have-read",
    fallbackBackgroundColor: "#304878",
    fallbackTextColor: "#d8e8ff",
    isbn: "",
    url: "",
  },
  {
    id: 30,
    title: "Die Tiny Habits Methode",
    author: "Dr. BJ Fogg",
    rating: 4,
    status: "have-read",
    fallbackBackgroundColor: "#005c48",
    fallbackTextColor: "#c0f0e4",
    isbn: "3442718694",
    url: "",
  },
  {
    id: 31,
    title: "Also sprach Zaratustra",
    author: "Friedrich Nietzsche",
    rating: 3,
    status: "currently-reading",
    fallbackBackgroundColor: "#1e1e2e",
    fallbackTextColor: "#d8d8f0",
    isbn: "",
    url: "",
    related: [53, 60],
  },
  {
    id: 32,
    title: "Veronika beschließt zu sterben",
    author: "Paulo Coelho",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#5c0030",
    fallbackTextColor: "#ffc8dc",
    isbn: "",
    url: "",
    related: [33],
  },
  {
    id: 33,
    title: "Der Alchemist",
    author: "Paulo Coelho",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#7a4a00",
    fallbackTextColor: "#fff0c0",
    isbn: "",
    url: "",
    related: [32],
  },
  {
    id: 34,
    title: "How Will You Measure Your Life?",
    author: "Clayton Christensen, James Allworth, Karen Dillon",
    status: "will-read",
    fallbackBackgroundColor: "#283878",
    fallbackTextColor: "#d0d8ff",
    isbn: "",
    url: "",
  },
  {
    id: 35,
    title: "A Simpler Life",
    author: "The School of Life",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#3a2a18",
    fallbackTextColor: "#f0e5d0",
    isbn: "1912891689",
    url: "",
    related: [25, 28, 43],
  },
  {
    id: 36,
    title: "Und Nietzsche weinte",
    author: "Irvin D. Yalom",
    status: "will-read",
    fallbackBackgroundColor: "#2c2a40",
    fallbackTextColor: "#d8d5f5",
    isbn: "",
    url: "",
    related: [37],
  },
  {
    id: 37,
    title: "Die Schopenhauer-Kur",
    author: "Irvin D. Yalom",
    status: "will-read",
    fallbackBackgroundColor: "#241820",
    fallbackTextColor: "#e8d5e0",
    isbn: "",
    url: "",
    related: [36],
  },
  {
    id: 38,
    title: "Being Happy",
    author: "Epicurus",
    status: "will-read",
    fallbackBackgroundColor: "#284830",
    fallbackTextColor: "#d0f0d8",
    isbn: "",
    url: "",
    related: [61],
  },
  {
    id: 39,
    title: "Saturday",
    author: "Ian McEwan",
    status: "will-read",
    fallbackBackgroundColor: "#2a3060",
    fallbackTextColor: "#d5d8f8",
    isbn: "",
    url: "",
  },
  {
    id: 40,
    title: "Surrounded by Idiots",
    author: "Thomas Erikson",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#5a1800",
    fallbackTextColor: "#ffd5b8",
    isbn: "9781250179630",
    url: "",
  },
  // {
  //   id: 41,
  //   title: "Weite",
  //   author: "Wolfram Secco",
  //   status: "will-read",
  //   fallbackBackgroundColor: "#0a3a50",
  //   fallbackTextColor: "#c0e0f0",
  //   isbn: "",
  //   url: "",
  // },
  // {
  //   id: 42,
  //   title: "Der Kleine Prinz",
  //   author: "Antoine De Saint-Exupéry",
  //   status: "will-read",
  //   fallbackBackgroundColor: "#0a4080",
  //   fallbackTextColor: "#c8ddf8",
  //   isbn: "",
  //   url: "",
  // },
  {
    id: 43,
    title: "Why You Will Marry the Wrong Person",
    author: "The School of Life",
    status: "will-read",
    fallbackBackgroundColor: "#680c30",
    fallbackTextColor: "#ffd0e0",
    isbn: "",
    url: "",
    related: [25, 28, 35],
  },
  {
    id: 44,
    title: "The Power of Words",
    author: "Simone Weil",
    status: "will-read",
    fallbackBackgroundColor: "#1a1a2e",
    fallbackTextColor: "#c8c8f0",
    isbn: "",
    url: "",
  },
  {
    id: 45,
    title: "Siddharta",
    author: "Hermann Hesse",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#8c5000",
    fallbackTextColor: "#fff3d0",
    isbn: "9783518366820",
    url: "",
  },
  {
    id: 46,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    rating: 3,
    status: "have-read",
    fallbackBackgroundColor: "#1a3a1a",
    fallbackTextColor: "#c8ecc8",
    isbn: "9780062316097",
    url: "",
  },
  {
    id: 47,
    title: "Über das Mitleid",
    author: "Arthur Schopenhauer",
    status: "currently-reading",
    fallbackBackgroundColor: "#2c2a38",
    fallbackTextColor: "#d8d5e8",
    isbn: "",
    url: "",
    related: [62],
  },
  {
    id: 48,
    title: "Die Verwandlung",
    author: "Franz Kafka",
    status: "will-read",
    fallbackBackgroundColor: "#1e2820",
    fallbackTextColor: "#d5e8d0",
    isbn: "",
    url: "",
  },
  {
    id: 49,
    title: "Anatomie der menschlichen Destruktivität",
    author: "Erich Fromm",
    status: "will-read",
    fallbackBackgroundColor: "#2a1a30",
    fallbackTextColor: "#e0d0e8",
    isbn: "",
    url: "",
    related: [67, 68],
  },
  {
    id: 50,
    title: "Multiple Intelligences",
    author: "Howard E. Gardner",
    status: "will-read",
    fallbackBackgroundColor: "#003850",
    fallbackTextColor: "#b8d8ee",
    isbn: "",
    url: "",
  },
  {
    id: 51,
    title: "What Design Can't Do",
    author: "Silvio Lorusso",
    status: "currently-reading",
    fallbackBackgroundColor: "#1a1a1a",
    fallbackTextColor: "#f0f0f0",
    isbn: "",
    url: "",
  },
  {
    id: 52,
    title: "Antifragile",
    author: "Nassim Nicholas Taleb",
    status: "will-read",
    fallbackBackgroundColor: "#1a2a1a",
    fallbackTextColor: "#d0e8d0",
    isbn: "9781400067824",
    url: "",
  },
  {
    id: 53,
    title: "Jenseits von Gut und Böse",
    author: "Friedrich Nietzsche",
    status: "will-read",
    fallbackBackgroundColor: "#2a1818",
    fallbackTextColor: "#f0d5d5",
    isbn: "",
    url: "",
    related: [31, 60],
  },
  {
    id: 54,
    title: "Leviathan",
    author: "Thomas Hobbes",
    status: "will-read",
    fallbackBackgroundColor: "#101838",
    fallbackTextColor: "#c0c5e8",
    isbn: "",
    url: "",
  },
  {
    id: 55,
    title: "Über die Regierung",
    author: "John Locke",
    status: "will-read",
    fallbackBackgroundColor: "#1a2a18",
    fallbackTextColor: "#d0e5d0",
    isbn: "",
    url: "",
  },
  {
    id: 56,
    title: "Vom Gesellschaftsvertrag",
    author: "Jean-Jacques Rousseau",
    status: "will-read",
    fallbackBackgroundColor: "#281a10",
    fallbackTextColor: "#ead5c0",
    isbn: "",
    url: "",
  },
  {
    id: 57,
    title: "Entweder – Oder",
    author: "Søren Kierkegaard",
    status: "will-read",
    fallbackBackgroundColor: "#2a1828",
    fallbackTextColor: "#e8d0e5",
    isbn: "",
    url: "",
  },
  {
    id: 58,
    title: "Wieviel Erde braucht der Mensch?",
    author: "Leo Tolstoi",
    status: "wanna-buy",
    fallbackBackgroundColor: "#1a2e10",
    fallbackTextColor: "#d5eacc",
    isbn: "",
    url: "",
  },
  {
    id: 59,
    title: "Der Spieler",
    author: "Fjodor Dostojewski",
    status: "wanna-buy",
    fallbackBackgroundColor: "#2a0a30",
    fallbackTextColor: "#e8c8f5",
    isbn: "",
    url: "",
    related: [65],
  },
  {
    id: 60,
    title: "Der Antichrist",
    author: "Friedrich Nietzsche",
    status: "wanna-buy",
    fallbackBackgroundColor: "#380a0a",
    fallbackTextColor: "#f5c8c8",
    isbn: "",
    url: "",
    related: [31, 53],
  },
  {
    id: 61,
    title: "The Art of Happiness",
    author: "Epicurus",
    status: "wanna-buy",
    fallbackBackgroundColor: "#484000",
    fallbackTextColor: "#f8f0cc",
    isbn: "",
    url: "",
    related: [38],
  },
  {
    id: 62,
    title: "Die Kunst, Recht zu behalten",
    author: "Arthur Schopenhauer",
    status: "wanna-buy",
    fallbackBackgroundColor: "#1e1818",
    fallbackTextColor: "#e8d8d0",
    isbn: "",
    url: "",
    related: [47],
  },
  {
    id: 63,
    title: "The Art of Doing Science and Engineering",
    author: "Richard Hamming",
    status: "wanna-buy",
    fallbackBackgroundColor: "#0a1e3a",
    fallbackTextColor: "#c0d0e8",
    isbn: "",
    url: "",
  },
  {
    id: 64,
    title: "The Creative Act: A Way of Being",
    author: "Rick Rubin",
    status: "currently-reading",
    fallbackBackgroundColor: "#2a0a20",
    fallbackTextColor: "#f0d0e8",
    isbn: "",
    url: "",
  },
  {
    id: 65,
    title: "Schuld und Sühne",
    author: "Fjodor Dostojewski",
    status: "currently-reading",
    fallbackBackgroundColor: "#2e1a10",
    fallbackTextColor: "#ead5c0",
    isbn: "",
    url: "",
    related: [59],
  },
  {
    id: 66,
    title: "Massenpsychologie und Ich-Analyse",
    author: "Sigmund Freud",
    status: "wanna-buy",
    fallbackBackgroundColor: "#1a1040",
    fallbackTextColor: "#d0c8f0",
    isbn: "",
    url: "",
  },
  {
    id: 67,
    title: "Die Kunst des Liebens",
    author: "Erich Fromm",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#700a30",
    fallbackTextColor: "#ffe0ea",
    isbn: "9783423361026",
    url: "",
    related: [49, 68],
  },
  {
    id: 68,
    title: "Die Seele des Menschen",
    author: "Erich Fromm",
    rating: 5,
    status: "have-read",
    fallbackBackgroundColor: "#202030",
    fallbackTextColor: "#d5d5e8",
    isbn: "",
    url: "",
    related: [49, 67],
  },
  {
    id: 69,
    title: "1984",
    author: "George Orwell",
    status: "wanna-buy",
    fallbackBackgroundColor: "#0a1e3c",
    fallbackTextColor: "#b8ccee",
    isbn: "9780451524935",
    url: "",
  },
];

export const BOOK_BY_ID = new Map<number, Book>(BOOKS.map((b) => [b.id, b]));

// ─────────────────────────────────────────────────────────────────────────────
// Store
// ─────────────────────────────────────────────────────────────────────────────

interface BooksStore {
  focusedBook: Book | null;
  focusedIdx: number | null;
  hoveredBook: Book | null;

  // Actions
  setFocused: (idx: number) => void;
  clearFocus: () => void;
  navigateNext: () => void;
  navigatePrev: () => void;
  navigateToBookId: (id: number) => void;
  setHoveredBook: (book: Book | null) => void;

  // Selectors
  canNavigateNext: () => boolean;
  canNavigatePrev: () => boolean;
}

export const useBooksStore = create<BooksStore>()(
  devtools(
    (set, get) => ({
      focusedBook: null,
      focusedIdx: null,
      hoveredBook: null,

      setFocused: (idx) =>
        set({
          focusedIdx: idx,
          focusedBook: BOOKS[idx] ?? null,
        }),

      clearFocus: () =>
        set({
          focusedBook: null,
          focusedIdx: null,
        }),

      navigateNext: () => {
        const { focusedIdx } = get();
        if (focusedIdx === null) return;
        const next = focusedIdx + 1;
        if (next < BOOKS.length)
          set({ focusedIdx: next, focusedBook: BOOKS[next] });
      },

      navigatePrev: () => {
        const { focusedIdx } = get();
        if (focusedIdx === null) return;
        const prev = focusedIdx - 1;
        if (prev >= 0) set({ focusedIdx: prev, focusedBook: BOOKS[prev] });
      },

      navigateToBookId: (id) => {
        const idx = BOOKS.findIndex((b) => b.id === id);
        if (idx !== -1) set({ focusedIdx: idx, focusedBook: BOOKS[idx] });
      },

      setHoveredBook: (book) => set({ hoveredBook: book }),

      canNavigateNext: () => {
        const { focusedIdx } = get();
        return focusedIdx !== null && focusedIdx < BOOKS.length - 1;
      },

      canNavigatePrev: () => {
        const { focusedIdx } = get();
        return focusedIdx !== null && focusedIdx > 0;
      },
    }),
    { name: "books-store" },
  ),
);
