import { Theme } from "./gameStore";

export const FISHEYE_CONFIG = {
  MIN: 0.1,
  MAX: 0.8,
  DEFAULT: 0.3,
  STEP: 0.05,
} as const;

export const THEME_IDS = {
  DEFAULT: "DEFAULT",
  DARK: "DARK",
  PASTEL: "PASTEL",
  NEON: "NEON",
  // CUSTOM: "CUSTOM",
} as const;

export const THEME_CONFIG: Record<keyof typeof THEME_IDS, Theme> = {
  [THEME_IDS.DEFAULT]: {
    id: THEME_IDS.DEFAULT,
    name: "Im Hellen",
    description: "The original theme",
    active: true,
    preview: false,
    colors: {
      primary: "#212121",
      secondary: "#4178F7",
      accent: "#FFD700",
      background: "#212121",
      text: "#ffffff",
    },
    // planetColors: ["#bdbfd8", "#c3c3ce", "#efeef5"],
    planetColors: ["#ffffff", "#C5BDD5", "#85799F"],
    counterColor: "#ffffff",
    blobColor: "#ffffff",
    outlineColor: "#000000",
    eyeColor: "#000000",
    chatColor: "#4178F7",
  },
  [THEME_IDS.DARK]: {
    id: THEME_IDS.DARK,
    name: "Im Dunklen",
    description: "A sleek dark theme with inverted colors",
    active: false,
    preview: false,
    colors: {
      primary: "#151417",
      secondary: "#151417",
      accent: "#FFD700",
      background: "#151417",
      text: "#ffffff",
    },
    planetColors: ["#09080a", "#1a1a1a", "#202023"],
    counterColor: "#1b191d",
    blobColor: "#151519",
    outlineColor: "#3f3e41",
    eyeColor: "#97969b",
    chatColor: "#333236",
  },
  [THEME_IDS.PASTEL]: {
    id: THEME_IDS.PASTEL,
    name: "Im Grünen",
    description: "A soft pastel theme",
    preview: false,
    active: false,
    colors: {
      primary: "#515B40",
      secondary: "#297301",
      accent: "#FFD700",
      background: "#ffffff",
      text: "#f8fcf1",
    },
    planetColors: ["#FFE5E5", "#E5FFE5", "#E5F0FF"],
    counterColor: "#CCF4B6",
    blobColor: "#FEF8DF",
    outlineColor: "#5B482A",
    eyeColor: "#5B482A",
    chatColor: "#867e5d",
  },
  [THEME_IDS.NEON]: {
    id: THEME_IDS.NEON,
    name: "Im Bunten",
    description: "A vibrant neon theme",
    preview: false,
    active: false,
    colors: {
      primary: "#0000ff",
      secondary: "#FF3FF9",
      accent: "#ff00f7",
      background: "#002fff",
      text: "#ffffff",
    },
    planetColors: ["#ADECDE", "#adc8ec", "#2a2a2a"], // Dark planet
    counterColor: "#d72809",
    blobColor: "#ffc155",
    outlineColor: "#000000",
    eyeColor: "#0a12ed",
    chatColor: "#FF00EE",
  },
  // [THEME_IDS.CUSTOM]: {
  //   id: THEME_IDS.CUSTOM,
  //   name: "Custom",
  //   description: "Create your own theme",
  //   preview: false,
  //   active: false,
  //   colors: {
  //     primary: "#2979FF",
  //     secondary: "#4285F4",
  //     accent: "#FFD700",
  //     background: "#ffffff",
  //     text: "#000000",
  //   },
  //   planetColors: ["#ffffff", "#C5BDD5", "#85799F"],
  //   counterColor: "#2979FF",
  //   blobColor: "#ffffff",
  //   outlineColor: "#000000",
  //   eyeColor: "#000000",
  // },
} as const;

export type ThemeId = keyof typeof THEME_CONFIG;
