/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { CameraControls, GLTF } from "three-stdlib";
import { calculateAcceleratedRotation } from "@/utils/math";
import { useFrame } from "@react-three/fiber";
import {
  CAMERA_Y_POSITION,
  VISIBLE_OPTIONS_CAMERA_ZOOM,
  HIDDEN_OPTIONS_CAMERA_ZOOM,
} from "./HeadNavigation";
import { Star3D } from "@/3d-objects/Star3D";
import { useDeviceOrientation } from "@/hooks/useDeviceOrientation";
import { useSpring, a } from "@react-spring/three";

type GLTFResult = GLTF & {
  nodes: {
    eyes002: THREE.Mesh;
    glasses002: THREE.Mesh;
    head001: THREE.Mesh;
  };
  materials: {
    eyes: THREE.MeshBasicMaterial;
    glasses: THREE.MeshBasicMaterial;
    skin: THREE.MeshBasicMaterial;
  };
};
const HEAD_POSITION_Y = 2;
const MAX_ROTATION_X = 0.9;
const MAX_ROTATION_Y = 0.9;

useGLTF.preload("./models/toon_head.glb");

export function ToonHead({
  onHeadClick,
  motionPermissionGranted: permissionGranted,
  isMobile,
  cameraControlsRef,
  showOptions,
}: {
  onHeadClick: () => void;
  motionPermissionGranted: boolean;
  isMobile: boolean;
  cameraControlsRef: React.RefObject<CameraControls>;
  showOptions: boolean;
}) {
  const headRef = useRef<THREE.Group>(null!);
  const starRef = useRef<THREE.Mesh>(null!);
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
  const [blinking, setBlinking] = useState(false);
  const { orientation, acceleration } = useDeviceOrientation();
  const [clickTimestamps, setClickTimestamps] = useState<number[]>([]);
  const [isTipsy, setIsTipsy] = useState(false);
  const tipsyStartTimeRef = useRef<number | null>(null);

  const { nodes, materials } = useGLTF("./models/toon_head.glb") as GLTFResult;

  // Keep a ref to spring api for fine-grained control
  const [spring, api] = useSpring(() => ({
    scale: [0, 0, 0], // start invisible
    config: { tension: 200, friction: 15 },
  }));

  // Trigger spawn animation once on mount
  useEffect(() => {
    api.start({
      scale: [1.2, 1.2, 1.2],
      delay: 1500,
      config: { tension: 300, friction: 10 },
    });
  }, []);

  // Track mouse position for head rotation
  useEffect(() => {
    const handleMouseMove = (event: MouseEvent) => {
      setMousePosition({
        x: (event.clientX / window.innerWidth) * 2 - 1,
        y: (event.clientY / window.innerHeight) * 2 - 1,
      });
    };
    window.addEventListener("mousemove", handleMouseMove);
    return () => window.removeEventListener("mousemove", handleMouseMove);
  }, []);

  // Blinking animation every 4-5 seconds
  useEffect(() => {
    const blinkInterval = setInterval(() => {
      setBlinking(true);
      setTimeout(() => setBlinking(false), 150);
    }, 4000 + Math.random() * 1000);
    return () => clearInterval(blinkInterval);
  }, []);

  // Animation for head movement and camera positioning
  useFrame(({ clock }, delta) => {
    // Handle device motion for mobile
    if (isMobile && orientation && acceleration && permissionGranted) {
      handleMobileMovement(clock, delta);
    } else {
      // Handle mouse movement for desktop
      handleDesktopMovement(clock, delta);
    }

    // Animate tipsy state
    if (isTipsy && tipsyStartTimeRef.current) {
      const elapsed = clock.getElapsedTime() - tipsyStartTimeRef.current / 1000;
      const wobble = Math.sin(elapsed * 10) * 0.5;
      headRef.current.rotation.z += wobble * delta;
    }

    if (isTipsy && starRef.current) {
      starRef.current.rotation.y += delta * 4;
      starRef.current.rotation.z += delta * 2;
    }
  });

  // Handle mobile device motion
  const handleMobileMovement = (clock: THREE.Clock, delta: number) => {
    const {
      targetRotX,
      targetRotY,
      targetRotZ,
      accelX,
      accelY,
      orientGamma,
      orientBeta,
    } = calculateAcceleratedRotation(acceleration, orientation);

    // Apply mobile specific head rotation
    applyHeadRotation(-targetRotY, -targetRotX, 0, delta);

    // Apply mobile specific head position (shake effect)
    applyMobileHeadPosition(
      clock,
      delta,
      accelX,
      accelY,
      orientGamma,
      orientBeta
    );

    // Set camera look-at for mobile
    // Using normalized direction vector approach
    const lookDirection = new THREE.Vector3(
      targetRotX,
      targetRotY,
      targetRotZ
    ).normalize();
    const cameraPosition = new THREE.Vector3(
      0,
      CAMERA_Y_POSITION,
      showOptions ? VISIBLE_OPTIONS_CAMERA_ZOOM : HIDDEN_OPTIONS_CAMERA_ZOOM
    );
    const target = cameraPosition.clone().add(lookDirection);

    cameraControlsRef.current.setLookAt(
      cameraPosition.x,
      cameraPosition.y,
      cameraPosition.z,
      target.x,
      target.y, // Keep the +2 offset from original code
      target.z,
      true
    );
  };

  // Handle desktop mouse movement
  const handleDesktopMovement = (clock: THREE.Clock, delta: number) => {
    // Calculate target rotations based on mouse position
    const targetRotY = mousePosition.x * MAX_ROTATION_X;
    const targetRotX = mousePosition.y * MAX_ROTATION_Y;
    const targetRotZ = -mousePosition.x * MAX_ROTATION_X;

    // Apply desktop specific head rotation
    applyHeadRotation(targetRotX, targetRotY, targetRotZ, delta);

    // Apply breathing animation for head position
    const floatY = Math.sin(clock.getElapsedTime() * 0.5) * 0.1;
    headRef.current.position.y = floatY + HEAD_POSITION_Y;

    // Set camera look-at for desktop
    const cursorPos = new THREE.Vector3(
      mousePosition.x * 0.2,
      mousePosition.y * 0.2,
      0
    );

    cameraControlsRef.current.setLookAt(
      0,
      CAMERA_Y_POSITION,
      showOptions ? VISIBLE_OPTIONS_CAMERA_ZOOM : HIDDEN_OPTIONS_CAMERA_ZOOM,
      cursorPos.x,
      cursorPos.y + 2,
      cursorPos.z,
      true
    );
  };

  // Common function to apply head rotation
  const applyHeadRotation = (
    rotX: number,
    rotY: number,
    rotZ: number,
    delta: number
  ) => {
    headRef.current.rotation.y = THREE.MathUtils.lerp(
      headRef.current.rotation.y,
      rotY,
      1 - Math.exp(-4 * delta)
    );
    headRef.current.rotation.x = THREE.MathUtils.lerp(
      headRef.current.rotation.x,
      rotX,
      1 - Math.exp(-4 * delta)
    );
    headRef.current.rotation.z = THREE.MathUtils.lerp(
      headRef.current.rotation.z,
      rotZ,
      1 - Math.exp(-3 * delta)
    );
  };

  // Mobile specific head position with shake effect
  const applyMobileHeadPosition = (
    clock: THREE.Clock,
    delta: number,
    accelX: number,
    accelY: number,
    orientGamma: number,
    orientBeta: number
  ) => {
    const shakeStrength = 0.6;
    const shakeOffsetX = THREE.MathUtils.clamp(
      accelX * shakeStrength,
      -0.4,
      0.4
    );
    const shakeOffsetY = THREE.MathUtils.clamp(
      accelY * shakeStrength,
      -0.4,
      0.4
    );

    const floatY = HEAD_POSITION_Y;

    headRef.current.position.x = THREE.MathUtils.lerp(
      headRef.current.position.x,
      shakeOffsetX + orientGamma * 0.2,
      1 - Math.exp(-2 * delta)
    );
    headRef.current.position.y = THREE.MathUtils.lerp(
      headRef.current.position.y,
      floatY + shakeOffsetY + orientBeta * 0.2,
      1 - Math.exp(-2 * delta)
    );
  };

  const onClick = () => {
    const now = Date.now();
    setClickTimestamps((prev) => {
      const recent = prev.filter((ts) => now - ts < 800);
      const updated = [...recent, now];
      if (updated.length >= 5) {
        setIsTipsy(true);
        tipsyStartTimeRef.current = now;
        setTimeout(() => setIsTipsy(false), 4000);
        return [];
      }
      return updated;
    });

    onHeadClick();
    api.start({
      scale: showOptions ? [1.2, 1.2, 1.2] : [0.7, 0.7, 0.7],
      config: { tension: 300, friction: 10 },
    });
  };

  return (
    <a.group
      ref={headRef}
      onClick={onClick}
      castShadow
      scale={spring.scale}
      rotation={[0, Math.PI, 0]}
      position={[0, 2, 0]}
    >
      <group position={[0, -0.5, 0.5]} scale={1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.eyes002.geometry}
          material={materials.eyes}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.glasses002.geometry}
          material={materials.glasses}
          position={[0, 0.65, 0.5]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[-0.0479, -0.0882, -0.0479]}
        >
          <meshToonMaterial color="black" />
        </mesh>

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.head001.geometry}
          material={materials.skin}
        />
      </group>

      {/* Spinning Stars */}
      {isTipsy &&
        [-0.4, 0, 0.4].map((offset, i) => (
          <Star3D position={[offset, 1.5 + (i % 2) * 0.1, offset * 0.5]} />
        ))}
    </a.group>
  );
}
