import type { Quest } from "../core/quests/types";
import { SHOP_ITEMS_QUEST_STACK_ID } from "../core/quests/constants";
import { ROUTE_IDS } from "./routes";

export const initialQuests: Quest[] = [
  {
    id: "auto_tap_level_10",
    title: "Passives Einkommen",
    description: "Bringe den Auto Tapper auf Level 10",
    icon: "⚙️",
    color: "#6B84FF",
    progress: 0,
    maxProgress: 10,
    reward: {
      type: "taps_reward",
      amount: 2000,
    },
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "custom",
    progressionKind: "milestone",
    trigger: {
      action: "auto_tap_level",
      value: 1,
    },
    showProgress: true,
    stackId: "automation_mastery",
    stackOrder: 1,
    stackTitle: "Passive Income",
    stackDescription: "Level up your core automation line.",
  },
  {
    id: "auto_tap_level_50",
    title: "Auto Tap Hoch 50",
    description: "Bringe den Auto Tapper auf Level 50",
    icon: "🏭",
    color: "#5D72F4",
    progress: 0,
    maxProgress: 50,
    reward: {
      type: "taps_reward",
      amount: 20000,
    },
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "custom",
    progressionKind: "milestone",
    trigger: {
      action: "auto_tap_level",
      value: 1,
    },
    showProgress: true,
    stackId: "automation_mastery",
    stackOrder: 2,
    stackTitle: "Automation Mastery",
    stackDescription: "Level up your core automation line.",
  },
  {
    id: "auto_tap_level_100",
    title: "Durchgespielt",
    description: "Maxe den Auto Tapper aus",
    icon: "🤖",
    color: "#5263D7",
    progress: 0,
    maxProgress: 100,
    // reward: {
    //   type: "taps_reward",
    //   amount: 150000,
    // },
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "custom",
    progressionKind: "milestone",
    trigger: {
      action: "auto_tap_level",
      value: 1,
    },
    showProgress: true,
    stackId: "automation_mastery",
    stackOrder: 3,
    stackTitle: "Automation Mastery",
    stackDescription: "Level up your core automation line.",
  },
  {
    id: "about_quest_2",
    title: "Sul Sul!",
    description: "Finde den Plumbob 💎",
    icon: "💎",
    color: "#C45B9F",
    progress: 0,
    maxProgress: 1,
    reward: {
      type: "item_reward",
      amount: "simsPlumbob",
    },
    completed: false,
    routeId: ROUTE_IDS.ABOUT,
    type: "interaction",
    progressionKind: "trigger",
    trigger: {
      action: "click_plumbob",
      value: 1,
    },
  },
  {
    id: "portfolio_quest_1",
    title: "Weltraumspaziergang",
    description: "Schau dir ein paar meiner kreativen Arbeiten an",
    icon: "✨",
    color: "#5C8BFF",
    progress: 0,
    maxProgress: 2,
    reward: {
      type: "taps_reward",
      amount: 15000,
    },
    completed: false,
    routeId: ROUTE_IDS.PORTFOLIO,
    type: "interaction",
    progressionKind: "goal",
    trigger: {
      action: "click_portfolio_item",
      value: 1,
    },
  },
  {
    id: "about_books_shelf_3",
    title: "Du bist, was du isst",
    description: "Schau dir meine Buchsammlung an",
    icon: "📚",
    color: "#3E8C7A",
    progress: 0,
    maxProgress: 3,
    reward: {
      type: "taps_reward",
      amount: 5000,
    },
    completed: false,
    routeId: ROUTE_IDS.ABOUT,
    type: "interaction",
    progressionKind: "goal",
    trigger: {
      action: "click_books",
      value: 1,
    },
    showProgress: true,
    stackId: "about_tour",
    stackOrder: 3,
    stackTitle: "Kennlernphase",
    stackDescription: "Explore the interactive objects in the About room.",
  },
  {
    id: "about_socials_1",
    title: "Web Bubbles",
    description: "Öffne die Socials-Kugel im About-Bereich",
    icon: "🌐",
    color: "#4A8CCF",
    progress: 0,
    maxProgress: 1,
    reward: {
      type: "taps_reward",
      amount: 5000,
    },
    completed: false,
    routeId: ROUTE_IDS.ABOUT,
    type: "interaction",
    progressionKind: "trigger",
    trigger: {
      action: "click_socials",
      value: 1,
    },
    stackId: "about_tour",
    stackOrder: 2,
    stackTitle: "About Tour",
    stackDescription: "Explore the interactive objects in the About room.",
  },
  {
    id: "about_desk_1",
    title: "3 Tage Wach",
    description: "Tap auf das DJ-Setup im About-Bereich",
    icon: "🖥️",
    color: "#5E86D9",
    progress: 0,
    maxProgress: 1,
    reward: {
      type: "taps_reward",
      amount: 2000,
    },
    completed: false,
    routeId: ROUTE_IDS.ABOUT,
    type: "interaction",
    progressionKind: "trigger",
    trigger: {
      action: "click_desk",
      value: 1,
    },
    stackId: "about_tour",
    stackOrder: 1,
    stackTitle: "About Tour",
    stackDescription: "Explore the interactive objects in the About room.",
  },
  {
    id: "about_box_1",
    title: "Interessant",
    description: "Interagiere mit der Kiste im About-Bereich",
    icon: "📦",
    color: "#7A9E52",
    progress: 0,
    maxProgress: 1,
    reward: {
      type: "taps_reward",
      amount: 2000,
    },
    completed: false,
    routeId: ROUTE_IDS.ABOUT,
    type: "interaction",
    progressionKind: "trigger",
    trigger: {
      action: "click_box",
      value: 1,
    },
    stackId: "about_tour",
    stackOrder: 4,
    stackTitle: "About Tour",
    stackDescription: "Explore the interactive objects in the About room.",
  },
  {
    id: "manual_taps_50",
    title: "Nur der Anfang",
    description: "Tappe 50 Mal selbst",
    icon: "🖐️",
    color: "#E07A4F",
    progress: 0,
    maxProgress: 50,
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "tap",
    progressionKind: "milestone",
    trigger: {
      action: "manual_taps_total",
      value: 1,
    },
    showProgress: true,
    stackId: "manual_taps",
    stackOrder: 1,
    stackTitle: "Manual Tap Milestones",
    stackDescription: "Build up your own tapping stamina.",
  },
  {
    id: "manual_taps_100",
    title: "Einhundertmal!",
    description: "Tappe 100 Mal selbst",
    icon: "✋",
    color: "#E38B53",
    progress: 0,
    maxProgress: 100,
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "tap",
    progressionKind: "milestone",
    trigger: {
      action: "manual_taps_total",
      value: 1,
    },
    showProgress: true,
    stackId: "manual_taps",
    stackOrder: 2,
    stackTitle: "Manual Tap Milestones",
    stackDescription: "Build up your own tapping stamina.",
  },
  {
    id: "manual_taps_1000",
    title: "Maschine",
    description: "Tappe 1000 Mal selbst",
    icon: "🔥",
    color: "#D9654A",
    progress: 0,
    maxProgress: 1000,
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "tap",
    progressionKind: "milestone",
    trigger: {
      action: "manual_taps_total",
      value: 1,
    },
    showProgress: true,
    stackId: "manual_taps",
    stackOrder: 3,
    stackTitle: "Manual Tap Milestones",
    stackDescription: "Build up your own tapping stamina.",
  },
  {
    id: "total_taps_1000",
    title: "Vierstellig",
    description: "Erreiche insgesamt 1.000 Taps",
    icon: "🔢",
    color: "#5F6BDA",
    progress: 0,
    maxProgress: 1000,
    completed: false,
    type: "tap",
    progressionKind: "milestone",
    trigger: {
      action: "taps_total",
      value: 1,
    },
    showProgress: true,
    stackId: "total_taps",
    stackOrder: 1,
    stackTitle: "Total Tap Milestones",
    stackDescription: "Reach long-term lifetime tap goals.",
  },
  {
    id: "total_taps_10000",
    title: "Fünfstellig",
    description: "Erreiche insgesamt 10.000 Taps",
    icon: "💯",
    color: "#5660D0",
    progress: 0,
    maxProgress: 10000,
    completed: false,
    type: "tap",
    progressionKind: "milestone",
    trigger: {
      action: "taps_total",
      value: 1,
    },
    showProgress: true,
    stackId: "total_taps",
    stackOrder: 2,
    stackTitle: "Total Tap Milestones",
    stackDescription: "Reach long-term lifetime tap goals.",
  },
  {
    id: "total_taps_1000000",
    title: "Millionär",
    description: "Erreiche insgesamt 1.000.000 Taps",
    icon: "🪙",
    color: "#A85BD2",
    progress: 0,
    maxProgress: 1000000,
    completed: false,
    type: "tap",
    progressionKind: "milestone",
    trigger: {
      action: "taps_total",
      value: 1,
    },
    showProgress: true,
    stackId: "total_taps",
    stackOrder: 3,
    stackTitle: "Total Tap Milestones",
    stackDescription: "Reach long-term lifetime tap goals.",
  },
  {
    id: "total_taps_1000000000000",
    title: "Jetz geht's erst richtig los",
    description: "Erreiche insgesamt 100.000.000 Taps",
    icon: "🚀",
    color: "#7D6BFF",
    progress: 0,
    maxProgress: 100000000,
    completed: false,
    type: "tap",
    progressionKind: "milestone",
    trigger: {
      action: "taps_total",
      value: 1,
    },
    showProgress: true,
    stackId: "total_taps",
    stackOrder: 4,
    stackTitle: "Total Tap Milestones",
    stackDescription: "Reach long-term lifetime tap goals.",
  },
  {
    id: "total_taps_1000000000000000",
    title: "Unglaublich",
    description: "Erreiche insgesamt 1.000.000.000.000 Taps",
    icon: "🌌",
    color: "#5E8BFF",
    progress: 0,
    maxProgress: 1000000000000,
    completed: false,
    type: "tap",
    progressionKind: "milestone",
    trigger: {
      action: "taps_total",
      value: 1,
    },
    showProgress: true,
    stackId: "total_taps",
    stackOrder: 5,
    stackTitle: "Total Tap Milestones",
    stackDescription: "Reach long-term lifetime tap goals.",
  },
  {
    id: "shop_buy_bob_item_1",
    title: "Sag einfach mashallah",
    description: "Kaufe ein Bob-Item im Shop",
    icon: "🧢",
    color: "#5BA85E",
    progress: 0,
    maxProgress: 1,
    reward: {
      type: "taps_reward",
      amount: 5000,
    },
    completed: false,
    type: "custom",
    progressionKind: "trigger",
    trigger: {
      action: "shop_buy_bob_item",
      value: 1,
    },
    stackId: SHOP_ITEMS_QUEST_STACK_ID,
    stackOrder: 1,
    stackTitle: "Shop Collector",
    stackDescription: "Buy one item from each shop category.",
  },
  {
    id: "shop_buy_tap_effect_1",
    title: "Game Juice",
    description: "Kauf einen Tap-Effekt im Shop",
    icon: "✨",
    color: "#44A69A",
    progress: 0,
    maxProgress: 1,
    reward: {
      type: "taps_reward",
      amount: 5000,
    },
    completed: false,
    type: "custom",
    progressionKind: "trigger",
    trigger: {
      action: "shop_buy_tap_effect",
      value: 1,
    },
    stackId: SHOP_ITEMS_QUEST_STACK_ID,
    stackOrder: 2,
    stackTitle: "Shop Collector",
    stackDescription: "Buy one item from each shop category.",
  },
  {
    id: "shop_buy_world_1",
    title: "Matrix",
    description: "Kaufe eine Welt im Shop",
    icon: "🌍",
    color: "#4A8E6A",
    progress: 0,
    maxProgress: 1,
    reward: {
      type: "taps_reward",
      amount: 12000,
    },
    completed: false,
    type: "custom",
    progressionKind: "trigger",
    trigger: {
      action: "shop_buy_world",
      value: 1,
    },
    stackId: SHOP_ITEMS_QUEST_STACK_ID,
    stackOrder: 3,
    stackTitle: "Shop Collector",
    stackDescription: "Buy one item from each shop category.",
  },
  {
    id: "routes_purchased_1",
    title: "Paywall",
    description: "Schalte deine erste Route frei",
    icon: "🧭",
    color: "#4D7EDB",
    progress: 0,
    maxProgress: 1,
    // reward: {
    //   type: "taps_reward",
    //   amount: 5000,
    // },
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "custom",
    progressionKind: "milestone",
    trigger: {
      action: "routes_purchased_total",
      value: 1,
    },
    showProgress: true,
    stackId: "route_unlocks",
    stackOrder: 1,
    stackTitle: "Route Explorer",
    stackDescription: "Unlock new routes to expand your world.",
  },
  {
    id: "routes_purchased_3",
    title: "Alles gesehen",
    description: "Schalte alle Routen frei",
    icon: "🗺️",
    color: "#3C67BF",
    progress: 0,
    maxProgress: 3,
    reward: {
      type: "taps_reward",
      amount: 20000,
    },
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "custom",
    progressionKind: "milestone",
    trigger: {
      action: "routes_purchased_total",
      value: 1,
    },
    showProgress: true,
    stackId: "route_unlocks",
    stackOrder: 2,
    stackTitle: "Route Explorer",
    stackDescription: "Unlock new routes to expand your world.",
  },
  {
    id: "playtime_60s",
    title: "Nur ganz kurz noch",
    description: "Spiele insgesamt 2 Minuten",
    icon: "⏱️",
    color: "#D99844",
    progress: 0,
    maxProgress: 120,
    reward: {
      type: "taps_reward",
      amount: 2500,
    },
    completed: false,
    type: "time",
    progressionKind: "milestone",
    trigger: {
      action: "playtime_seconds",
      value: 1,
    },
    showProgress: true,
    stackId: "playtime",
    stackOrder: 1,
    stackTitle: "Playtime Milestones",
    stackDescription: "Stay in the game to unlock endurance rewards.",
  },
  {
    id: "playtime_600s",
    title: "Hooked",
    description: "Spiele insgesamt 5 Minuten",
    icon: "⌛",
    color: "#CC7A35",
    progress: 0,
    maxProgress: 300,
    reward: {
      type: "taps_reward",
      amount: 8000,
    },
    completed: false,
    type: "time",
    progressionKind: "milestone",
    trigger: {
      action: "playtime_seconds",
      value: 1,
    },
    showProgress: true,
    stackId: "playtime",
    stackOrder: 2,
    stackTitle: "Playtime Milestones",
    stackDescription: "Stay in the game to unlock endurance rewards.",
  },
  {
    id: "playtime_1800s",
    title: "Süchtig",
    description: "Spiele insgesamt 10 Minuten",
    icon: "🪴",
    color: "#C36C2F",
    progress: 0,
    maxProgress: 600,
    reward: {
      type: "taps_reward",
      amount: 15000,
    },
    completed: false,
    type: "time",
    progressionKind: "milestone",
    trigger: {
      action: "playtime_seconds",
      value: 1,
    },
    showProgress: true,
    stackId: "playtime",
    stackOrder: 3,
    stackTitle: "Playtime Milestones",
    stackDescription: "Stay in the game to unlock endurance rewards.",
  },
  {
    id: "upgrade_levels_25",
    title: "Upgrade Meister",
    description: "Erreiche insgesamt 25 Upgrade-Level",
    icon: "🧰",
    color: "#4F95C8",
    progress: 0,
    maxProgress: 25,
    reward: {
      type: "taps_reward",
      amount: 5000,
    },
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "custom",
    progressionKind: "milestone",
    trigger: {
      action: "upgrade_levels_total",
      value: 1,
    },
    showProgress: true,
    stackId: "upgrade_levels",
    stackOrder: 1,
    stackTitle: "Upgrade Mastery",
    stackDescription: "Keep investing across the whole upgrade tree.",
  },
  {
    id: "upgrade_levels_100",
    title: "Club 100",
    description: "Erreiche insgesamt 100 Upgrade-Level",
    icon: "🔩",
    color: "#437FB3",
    progress: 0,
    maxProgress: 100,
    reward: {
      type: "taps_reward",
      amount: 40000,
    },
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "custom",
    progressionKind: "milestone",
    trigger: {
      action: "upgrade_levels_total",
      value: 1,
    },
    showProgress: true,
    stackId: "upgrade_levels",
    stackOrder: 2,
    stackTitle: "Upgrade Mastery",
    stackDescription: "Keep investing across the whole upgrade tree.",
  },
  {
    id: "upgrade_levels_200",
    title: "Super Tapper",
    description: "Erreiche insgesamt 200 Upgrade-Level",
    icon: "🛠️",
    color: "#356A98",
    progress: 0,
    maxProgress: 200,
    reward: {
      type: "taps_reward",
      amount: 200000,
    },
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "custom",
    progressionKind: "milestone",
    trigger: {
      action: "upgrade_levels_total",
      value: 1,
    },
    showProgress: true,
    stackId: "upgrade_levels",
    stackOrder: 3,
    stackTitle: "Upgrade Mastery",
    stackDescription: "Keep investing across the whole upgrade tree.",
  },
  {
    id: "auto_tap_rate_100",
    title: "100 pro Sekunde",
    description: "Erreiche 100 Auto-Taps pro Sekunde",
    icon: "📈",
    color: "#3DAA8D",
    progress: 0,
    maxProgress: 100,
    reward: {
      type: "taps_reward",
      amount: 6000,
    },
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "custom",
    progressionKind: "milestone",
    trigger: {
      action: "auto_tap_rate",
      value: 1,
    },
    showProgress: true,
    stackId: "auto_tap_rate",
    stackOrder: 1,
    stackTitle: "Automation Output",
    stackDescription: "Push your passive tap production higher.",
  },
  {
    id: "auto_tap_rate_1000",
    title: "Mega Tapper",
    description: "Erreiche 1.000 Auto-Taps pro Sekunde",
    icon: "⚡",
    color: "#349A80",
    progress: 0,
    maxProgress: 1000,
    reward: {
      type: "taps_reward",
      amount: 30000,
    },
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "custom",
    progressionKind: "milestone",
    trigger: {
      action: "auto_tap_rate",
      value: 1,
    },
    showProgress: true,
    stackId: "auto_tap_rate",
    stackOrder: 2,
    stackTitle: "Automation Output",
    stackDescription: "Push your passive tap production higher.",
  },
  {
    id: "auto_tap_rate_10000",
    title: "Giga Tapper",
    description: "Erreiche 10.000 Auto-Taps pro Sekunde",
    icon: "🚂",
    color: "#2A836D",
    progress: 0,
    maxProgress: 10000,
    reward: {
      type: "taps_reward",
      amount: 175000,
    },
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "custom",
    progressionKind: "milestone",
    trigger: {
      action: "auto_tap_rate",
      value: 1,
    },
    showProgress: true,
    stackId: "auto_tap_rate",
    stackOrder: 3,
    stackTitle: "Automation Output",
    stackDescription: "Push your passive tap production higher.",
  },
  {
    id: "tap_multiplier_5",
    title: "Penta Tap",
    description: "Erreiche 5x Tap-Power",
    icon: "🫵",
    color: "#D76F4C",
    progress: 0,
    maxProgress: 5,
    reward: {
      type: "taps_reward",
      amount: 8000,
    },
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "custom",
    progressionKind: "milestone",
    trigger: {
      action: "tap_multiplier",
      value: 1,
    },
    showProgress: true,
    stackId: "tap_multiplier",
    stackOrder: 1,
    stackTitle: "Tap Power",
    stackDescription: "Keep making every manual tap hit harder.",
  },
  {
    id: "tap_multiplier_20",
    title: "Zwanni Tap",
    description: "Erreiche 20x Tap-Power",
    icon: "💥",
    color: "#CC6242",
    progress: 0,
    maxProgress: 20,
    reward: {
      type: "taps_reward",
      amount: 40000,
    },
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "custom",
    progressionKind: "milestone",
    trigger: {
      action: "tap_multiplier",
      value: 1,
    },
    showProgress: true,
    stackId: "tap_multiplier",
    stackOrder: 2,
    stackTitle: "Tap Power",
    stackDescription: "Keep making every manual tap hit harder.",
  },
  {
    id: "tap_multiplier_50",
    title: "Fuffi Tap",
    description: "Erreiche 50x Tap-Power",
    icon: "🚨",
    color: "#BF5538",
    progress: 0,
    maxProgress: 50,
    reward: {
      type: "taps_reward",
      amount: 175000,
    },
    completed: false,
    routeId: ROUTE_IDS.HOME,
    type: "custom",
    progressionKind: "milestone",
    trigger: {
      action: "tap_multiplier",
      value: 1,
    },
    showProgress: true,
    stackId: "tap_multiplier",
    stackOrder: 3,
    stackTitle: "Tap Power",
    stackDescription: "Keep making every manual tap hit harder.",
  },
  {
    id: "minigames_flappy_points_10",
    title: "Flappy Bobbie",
    description: "Erziele 10 Punkte im Flappy Bird Minigame",
    icon: "🐦",
    color: "#4BA7F2",
    progress: 0,
    maxProgress: 10,
    reward: {
      type: "taps_reward",
      amount: 10000,
    },
    completed: false,
    routeId: ROUTE_IDS.MINIGAMES,
    type: "interaction",
    progressionKind: "goal",
    trigger: {
      action: "minigames_flappy_score",
      value: 1,
    },
    showProgress: true,
  },
  {
    id: "minigames_slot_wins_5",
    title: "Alles wieder reingeholt",
    description: "Gewinne am Slotautomaten",
    icon: "🏆",
    color: "#F0A44B",
    progress: 0,
    maxProgress: 1,
    reward: {
      type: "taps_reward",
      amount: 1000000,
    },
    completed: false,
    routeId: ROUTE_IDS.MINIGAMES,
    type: "interaction",
    progressionKind: "trigger",
    trigger: {
      action: "minigames_slot_win",
      value: 1,
    },
  },
];
