/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useViewStore } from "@/store";
import { useFloatingBar } from "@/layout/FloatingBar";
import { getLocale } from "@/i18n";
import { bookTableMessages } from "./bookTable.messages";

type GLTFResult = GLTF & {
  nodes: {
    ["Node-Mesh"]: THREE.Mesh;
    ["Node-Mesh_1"]: THREE.Mesh;
  };
  materials: {
    mat23: THREE.MeshStandardMaterial;
    mat24: THREE.MeshStandardMaterial;
  };
};

const PATH = "/gltf/table.glb";
useGLTF.preload(PATH);

interface Props {
  position: [number, number, number];
  rotation?: [number, number, number];
  scale?: [number, number, number];
}

export const BookTable = ({ scale = [1, 1, 1], ...props }: Props) => {
  const group = useRef<THREE.Group>(null!);
  const { nodes, materials } = useGLTF(PATH) as GLTFResult;

  const { currentView } = useViewStore();
  const { setHoveredObject } = useFloatingBar();

  const handlePointerEnter = (e: any) => {
    e.stopPropagation();
    const locale = getLocale();

    if (currentView !== "bookshelf")
      setHoveredObject({
        title: bookTableMessages[locale].floatingLabel,
      });
  };

  const handlePointerLeave = () => {
    setHoveredObject(null);
  };

  return (
    <group
      ref={group}
      scale={scale}
      castShadow
      receiveShadow
      position={props.position}
      rotation={props.rotation}
      onPointerEnter={handlePointerEnter}
      onPointerLeave={handlePointerLeave}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Node-Mesh"].geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Node-Mesh_1"].geometry}
        material={materials.mat24}
      />
    </group>
  );
};
