import type { SocialLink } from "./types";

export const SOCIAL_LINKS: SocialLink[] = [
  {
    id: "github",
    label: "GitHub",
    href: "https://github.com/eduardlotz",
    handle: "github.com/eduardlotz",
    color: "#171717",
    sticker: "GH",
    textColor: "#171717",
  },
  {
    id: "x",
    label: "Twitter (X)",
    href: "https://x.com/captainlowie",
    handle: "x.com/captainlowie",
    color: "#2fb2ee",
    sticker: "X",
    textColor: "#ffffff",
  },
  {
    id: "instagram",
    label: "Instagram",
    href: "https://instagram.com/captainlowie",
    handle: "instagram.com/captainlowie",
    color: "#861476",
    sticker: "IG",
    textColor: "#ffffff",
  },
  {
    id: "soundcloud",
    label: "Soundcloud",
    href: "https://soundcloud.com/captainlowie",
    handle: "soundcloud.com/captainlowie",
    color: "#ff8d22",
    sticker: "SC",
    textColor: "#ffffff",
  },
  {
    id: "cosmos",
    label: "Cosmos",
    href: "https://cosmos.so/edddie",
    handle: "cosmos.so/edddie",
    color: "#1f1f1f",
    sticker: "CO",
    textColor: "#ffffff",
  },
  {
    id: "linkedin",
    label: "LinkedIn",
    href: "https://linkedin.com/in/eduardlotz",
    handle: "linkedin.com/in/eduardlotz",
    color: "#315eb6",
    sticker: "in",
    textColor: "#ffffff",
  },
];
