import { BobItem } from "@/store";

export const initialBobItems: BobItem[] = [
  {
    id: "builderHelmet",
    name: "Baumeister",
    description: "Jo wir schaffen das!",
    cost: 900,
    purchased: false,
    enabled: false,
    type: "hat",
    icon: "👨‍🍳",
    category: "bob",
  },
  {
    id: "krustyKrabHat",
    name: "Burger Boy",
    description: "Ist da die Krosse Krabbe?",
    cost: 1_500,
    purchased: false,
    enabled: false,
    type: "hat",
    icon: "👨‍🍳",
    category: "bob",
  },
  {
    id: "afroHair",
    name: "Künstler",
    description: "Happy little accidents",
    cost: 2_400,
    purchased: false,
    enabled: false,
    type: "hat",
    icon: "👨‍🎨",
    category: "bob",
  },
  {
    id: "chickenLittleGlasses",
    name: "Brillenschlange",
    description: "Eddie's Brille",
    cost: 6_000,
    purchased: false,
    enabled: false,
    type: "accessory",
    icon: "🤓",
    category: "bob",
  },

  {
    id: "blackCap",
    name: "Cap",
    description: "Eddie's schwarze Kappe",
    cost: 9_500,
    purchased: false,
    enabled: false,
    type: "hat",
    icon: "🧢",
    category: "bob",
  },
  {
    id: "rastaBeanie",
    name: "Marley",
    cost: 25_000,
    purchased: false,
    enabled: false,
    type: "hat",
    icon: "🇯🇲",
    category: "bob",
  },
  {
    id: "astronautHelmet",
    name: "Astrobob",
    description: "Der Kindheitstraum",
    cost: 120_000,
    purchased: false,
    enabled: false,
    type: "hat",
    icon: "👨‍🚀",
    category: "bob",
  },
  {
    id: "simsPlumbob",
    name: "Sim",
    description: "Sul Sul",
    cost: 0,
    purchased: false,
    enabled: false,
    unlocked: false,
    type: "decoration",
    icon: "💎",
    category: "bob",
    detached: true,
  },
];
