import { DecorationItem } from "@/store";

export const initialDecorations: DecorationItem[] = [
  {
    id: "tree_3d",
    name: "Baum",
    description: "Ein Baum",
    cost: 1000,
    purchased: false,
    enabled: false,
    type: "3d",
    position: [0, -1, -5],
    scale: 1.5,
    color: "#FFD700",
    icon: "🌳",
  },
  {
    id: "grass_3d",
    name: "Gras ",
    description: "Touch it",
    cost: 10000,
    purchased: false,
    enabled: false,
    type: "3d",
    position: [0, -0.8, 0],
    scale: 1,
    icon: "🌿",
  },
  {
    id: "clouds_3d",
    name: "Wolken",
    description: "Vape Nations Legacy",
    cost: 5000,
    purchased: false,
    enabled: false,
    type: "3d",
    position: [0, -0.8, 0],
    scale: 1,
    icon: "☁️",
  },
];
