import { TapEffect } from "@/store";

export const initialTapEffects: TapEffect[] = [
  {
    id: "tap_effect_default",
    name: "Standard",
    description: "Weiße, graue und schwarze Punkte",
    cost: 0,
    purchased: true,
    type: "tapEffect",
    enabled: true,
    effectId: 0,
  },
  {
    id: "tap_effect_emojis",
    name: "Emojis",
    description: "Emoji-Partikel mit Augen, Feuer und Funkeln",
    cost: 750,
    purchased: false,
    type: "tapEffect",
    enabled: false,
    effectId: 5,
  },
  {
    id: "tap_effect_confetti",
    name: "Konfetti",
    description: "Farbige Konfetti-Partikel",
    cost: 1_200,
    purchased: false,
    type: "tapEffect",
    enabled: false,
    effectId: 1,
  },
  {
    id: "tap_effect_bubbles",
    name: "Blasen",
    description: "Leichte Seifenblasen mit sanftem Schweben",
    cost: 4_000,
    purchased: false,
    type: "tapEffect",
    enabled: false,
    effectId: 7,
  },
  {
    id: "tap_effect_hearts",
    name: "Herzen",
    description: "Herzen",
    cost: 6_500,
    purchased: false,
    type: "tapEffect",
    enabled: false,
    effectId: 2,
  },
  {
    id: "tap_effect_smoke",
    name: "Rauch",
    description: "Sanfte Rauchschwaden, die nach oben ziehen",
    cost: 15_000,
    purchased: false,
    type: "tapEffect",
    enabled: false,
    effectId: 6,
  },
  {
    id: "tap_effect_stars",
    name: "Sterne",
    description: "Sterne",
    cost: 28_000,
    purchased: false,
    type: "tapEffect",
    enabled: false,
    effectId: 3,
  },
  {
    id: "tap_effect_laser",
    name: "Laser",
    description: "Rote Laserblitze direkt aus der Mitte",
    cost: 60_000,
    purchased: false,
    type: "tapEffect",
    enabled: false,
    effectId: 4,
  },
];
