import { Upgrade } from "@/store";

export const initialTapUpgrades: Upgrade[] = [
  {
    id: "auto_tap_1",
    name: "Auto Tapper",
    description: "Lass Bob 1 Mal pro Sekunde für dich tippen",
    baseCost: 15,
    costMultiplier: 2.5,
    level: 0,
    maxLevel: 5,
    effect: { type: "autoTap", value: 1 },
    unlocked: true,
    icon: "🫵",
    category: "upgrades",
  },
  {
    id: "tap_multiplier_1",
    name: "Tap Multiplikator",
    description: "Verdopple deine Taps",
    baseCost: 50,
    costMultiplier: 5,
    level: 0,
    maxLevel: 5,
    effect: { type: "tapMultiplier", value: 2 },
    unlocked: true,
    icon: "💪",
    category: "upgrades",
  },
  //   {
  //     id: "auto_tap_2",
  //     name: "Super Auto Tapper",
  //     description: "Automatically taps 3 times per second",
  //     baseCost: 200,
  //     costMultiplier: 1.5,
  //     level: 0,
  //     maxLevel: 3,
  //     effect: { type: "autoTap", value: 3 },
  //     unlocked: false,
  //     icon: "⚡",
  //     category: "upgrades",
  //   },
  //   {
  //     id: "tap_multiplier_2",
  //     name: "Mega Tap Power",
  //     description: "Triples your tap power",
  //     baseCost: 1000,
  //     costMultiplier: 2.5,
  //     level: 0,
  //     maxLevel: 2,
  //     effect: { type: "tapMultiplier", value: 3 },
  //     unlocked: false,
  //     icon: "🔥",
  //     category: "upgrades",
  //   },
];

export const initialTapEffects: Upgrade[] = [
  {
    id: "tap_effect_default",
    name: "Default Tap Effect",
    description: "Classic white, grey, and black dots",
    baseCost: 0,
    costMultiplier: 1,
    level: 1,
    maxLevel: 1,
    effect: { type: "tapEffect", value: 0 },
    unlocked: true,
    icon: "⚪",
    category: "tapEffects",
    selected: true, // Default selected
  },
  {
    id: "tap_effect_confetti",
    name: "Confetti Effect",
    description: "Colorful confetti pieces",
    baseCost: 1500,
    costMultiplier: 1,
    level: 0,
    maxLevel: 1,
    effect: { type: "tapEffect", value: 1 },
    unlocked: false,
    icon: "🎉",
    category: "tapEffects",
    selected: false,
  },
  {
    id: "tap_effect_hearts",
    name: "Heart Effect",
    description: "Floating heart particles",
    baseCost: 2500,
    costMultiplier: 1,
    level: 0,
    maxLevel: 1,
    effect: { type: "tapEffect", value: 2 },
    unlocked: false,
    icon: "💖",
    category: "tapEffects",
    selected: false,
  },
  {
    id: "tap_effect_stars",
    name: "Star Effect",
    description: "Shining star particles",
    baseCost: 3500,
    costMultiplier: 1,
    level: 0,
    maxLevel: 1,
    effect: { type: "tapEffect", value: 3 },
    unlocked: false,
    icon: "⭐",
    category: "tapEffects",
    selected: false,
  },
];

export const initialWorldEffects: Upgrade[] = [
  {
    id: "environment_rain",
    name: "Rain Effect",
    description: "Adds a gentle rain particle effect",
    baseCost: 100,
    costMultiplier: 1,
    level: 0,
    maxLevel: 1,
    effect: { type: "environment", value: 0 },
    unlocked: false,
    icon: "🌧️",
    category: "environment",
    selected: false,
  },
  {
    id: "environment_clouds",
    name: "Cloud Effect",
    description: "Adds floating cloud particles",
    baseCost: 150,
    costMultiplier: 1,
    level: 0,
    maxLevel: 1,
    effect: { type: "environment", value: 1 },
    unlocked: false,
    icon: "☁️",
    category: "environment",
    selected: false,
  },
];

export const initialUpgrades: Upgrade[] = [
  ...initialTapUpgrades,
  ...initialTapEffects,
  ...initialWorldEffects,
] as const;
