import { Upgrade } from "@/store";

export const initialTapUpgrades: Upgrade[] = [
  {
    id: "auto_tap",
    name: "Auto Tapper",
    description: "Lass Bob 1 Mal pro Sekunde für dich tippen",
    baseCost: 15,
    costMultiplier: 1.13,
    level: 0,
    maxLevel: 100,
    effect: { type: "autoTap", value: 1 },
    unlocked: true,
  },
  {
    id: "bob_assistant",
    name: "Bob-Assistent",
    description: "Ein fleissiger Assistent tippt fuer dich",
    baseCost: 120,
    costMultiplier: 1.14,
    level: 0,
    maxLevel: 75,
    effect: { type: "autoTap", value: 8 },
    unlocked: true,
  },
  {
    id: "garden_gnome",
    name: "Gartenwichtel",
    description: "Wichtel sammeln Taps aus deinem Garten",
    baseCost: 900,
    costMultiplier: 1.145,
    level: 0,
    maxLevel: 70,
    effect: { type: "autoTap", value: 45 },
    unlocked: true,
  },
  {
    id: "greenhouse",
    name: "Gewaechshaus",
    description: "Automatisierte Pflanzen produzieren Taps",
    baseCost: 6_500,
    costMultiplier: 1.15,
    level: 0,
    maxLevel: 60,
    effect: { type: "autoTap", value: 260 },
    unlocked: true,
  },
  {
    id: "factory_line",
    name: "Fertigungsstrasse",
    description: "Eine Fabriklinie pumpt konstant Taps",
    baseCost: 45_000,
    costMultiplier: 1.155,
    level: 0,
    maxLevel: 50,
    effect: { type: "autoTap", value: 1_400 },
    unlocked: true,
  },
  {
    id: "logistics_hub",
    name: "Logistikzentrum",
    description: "Verteilt Tap-Produktion ueberall hin",
    baseCost: 300_000,
    costMultiplier: 1.16,
    level: 0,
    maxLevel: 40,
    effect: { type: "autoTap", value: 8_000 },
    unlocked: true,
  },
  {
    id: "quantum_lab",
    name: "Quantenlabor",
    description: "Instabile Experimente erzeugen viele Taps",
    baseCost: 2_500_000,
    costMultiplier: 1.165,
    level: 0,
    maxLevel: 30,
    effect: { type: "autoTap", value: 47_000 },
    unlocked: true,
  },
  {
    id: "temporal_engine",
    name: "Temporalmaschine",
    description: "Leiht sich Taps aus naher Zukunft",
    baseCost: 22_000_000,
    costMultiplier: 1.17,
    level: 0,
    maxLevel: 20,
    effect: { type: "autoTap", value: 280_000 },
    unlocked: true,
  },
  {
    id: "finger_training",
    name: "Fingertraining",
    description: "Verbessert die Staerke deiner manuellen Taps",
    baseCost: 40,
    costMultiplier: 1.15,
    level: 0,
    maxLevel: 25,
    effect: { type: "tapMultiplier", value: 1.08 },
    unlocked: true,
  },
  {
    id: "precision_gloves",
    name: "Praezisionshandschuhe",
    description: "Jeder Tap sitzt genauer und staerker",
    baseCost: 4_000,
    costMultiplier: 1.18,
    level: 0,
    maxLevel: 20,
    effect: { type: "tapMultiplier", value: 1.12 },
    unlocked: true,
  },
];
