import { Upgrade } from "@/store";

export const initialTapUpgrades: Upgrade[] = [
  {
    id: "auto_tap",
    name: "Auto Tapper",
    description: "Lass Bob 1 Mal pro Sekunde für dich tippen",
    baseCost: 15,
    costMultiplier: 1.15,
    level: 0,
    maxLevel: 100,
    effect: { type: "autoTap", value: 1 },
    unlocked: true,
  },
  {
    id: "bob_assistant",
    name: "Bob-Assistent",
    description: "Ein fleissiger Assistent tippt fuer dich",
    baseCost: 100,
    costMultiplier: 1.16,
    level: 0,
    maxLevel: 80,
    effect: { type: "autoTap", value: 5 },
    unlocked: true,
  },
  {
    id: "garden_gnome",
    name: "Gartenwichtel",
    description: "Wichtel sammeln Taps aus deinem Garten",
    baseCost: 1_100,
    costMultiplier: 1.17,
    level: 0,
    maxLevel: 70,
    effect: { type: "autoTap", value: 25 },
    unlocked: true,
  },
  {
    id: "greenhouse",
    name: "Gewaechshaus",
    description: "Automatisierte Pflanzen produzieren Taps",
    baseCost: 12_000,
    costMultiplier: 1.18,
    level: 0,
    maxLevel: 60,
    effect: { type: "autoTap", value: 120 },
    unlocked: true,
  },
  {
    id: "factory_line",
    name: "Fertigungsstrasse",
    description: "Eine Fabriklinie pumpt konstant Taps",
    baseCost: 130_000,
    costMultiplier: 1.19,
    level: 0,
    maxLevel: 50,
    effect: { type: "autoTap", value: 600 },
    unlocked: true,
  },
  {
    id: "logistics_hub",
    name: "Logistikzentrum",
    description: "Verteilt Tap-Produktion ueberall hin",
    baseCost: 1_400_000,
    costMultiplier: 1.2,
    level: 0,
    maxLevel: 40,
    effect: { type: "autoTap", value: 3_000 },
    unlocked: true,
  },
  {
    id: "quantum_lab",
    name: "Quantenlabor",
    description: "Instabile Experimente erzeugen viele Taps",
    baseCost: 20_000_000,
    costMultiplier: 1.21,
    level: 0,
    maxLevel: 30,
    effect: { type: "autoTap", value: 15_000 },
    unlocked: true,
  },
  {
    id: "temporal_engine",
    name: "Temporalmaschine",
    description: "Leiht sich Taps aus naher Zukunft",
    baseCost: 330_000_000,
    costMultiplier: 1.22,
    level: 0,
    maxLevel: 20,
    effect: { type: "autoTap", value: 75_000 },
    unlocked: true,
  },
  {
    id: "finger_training",
    name: "Fingertraining",
    description: "Verbessert die Staerke deiner manuellen Taps",
    baseCost: 50,
    costMultiplier: 1.18,
    level: 0,
    maxLevel: 30,
    effect: { type: "tapMultiplier", value: 1.12 },
    unlocked: true,
  },
  {
    id: "precision_gloves",
    name: "Praezisionshandschuhe",
    description: "Jeder Tap sitzt genauer und staerker",
    baseCost: 5_000,
    costMultiplier: 1.22,
    level: 0,
    maxLevel: 20,
    effect: { type: "tapMultiplier", value: 1.2 },
    unlocked: true,
  },
];
