import type { WorldItem } from "@/store";

const DEFAULT_WORLD_LIGHTING = {
  ambientIntensity: 2,
  directionalIntensity: 1.2,
} as const;

export const initialWorlds: WorldItem[] = [
  {
    id: "world_default",
    name: "Standard",
    description: "Der klassische Vorgarten mit Grid und blau-weißer Welt.",
    cost: 0,
    purchased: true,
    enabled: true,
    type: "world",
    icon: "🌐",
    scene: {
      skyColors: ["#c8f3ff", "#84c5ff"],
      gradientStops: [0, 0.5, 1],
      gradientColors: ["#ffffff", "#c5bdd5", "#85799f"],
      groundColor: "#e7edf8",
      accentColor: "#d8e1f2",
      models: ["default_home"],
      effects: ["default_grid"],
      lighting: DEFAULT_WORLD_LIGHTING,
    },
  },
  {
    id: "world_forest",
    name: "Wald",
    description: "Ein dichter Bob-Wald mit Wolken und Glühpunkten.",
    cost: 50_000,
    purchased: false,
    enabled: false,
    type: "world",
    icon: "🌲",
    scene: {
      skyColors: ["#c8f3ff", "#84c5ff"],
      gradientStops: [0, 0.35, 1],
      gradientColors: ["#8fd4ff", "#dff7ff", "#7abf7f"],
      groundColor: "#345d36",
      accentColor: "#86cf72",
      models: ["forest_grove", "forest_meadow"],
      effects: ["forest_fireflies", "forest_rain"],
      lighting: DEFAULT_WORLD_LIGHTING,
    },
  },
  {
    id: "world_city",
    name: "Stadt",
    description:
      "Eine New Yorker Skyline mit Brownstones, Autos und gelben Taxis.",
    cost: 100_000,
    purchased: false,
    enabled: false,
    type: "world",
    icon: "🏙️",
    scene: {
      skyColors: ["#c5dced", "#89b3d2"],
      gradientStops: [0, 0.45, 1],
      gradientColors: ["#96bbd6", "#dce8ec", "#b9c4c9"],
      groundColor: "#b5b8b3",
      accentColor: "#dbd5c4",
      models: ["city_blocks"],
      effects: [],
      lighting: DEFAULT_WORLD_LIGHTING,
    },
  },
  {
    id: "world_desert",
    name: "Wüste",
    description: "Warme Dünen, Kakteen und ein bisschen Staub in der Luft.",
    cost: 300_000,
    purchased: false,
    enabled: false,
    type: "world",
    icon: "🏜️",
    scene: {
      skyColors: ["#ffe0a8", "#ff9b63"],
      gradientStops: [0, 0.4, 1],
      gradientColors: ["#ffbb73", "#ffe3b2", "#d07b4a"],
      groundColor: "#c98943",
      accentColor: "#f0c36d",
      models: ["desert_dunes", "desert_pyramids"],
      effects: ["desert_sand"],
      lighting: DEFAULT_WORLD_LIGHTING,
    },
  },
  {
    id: "world_winter",
    name: "Winter",
    description: "Kalter Schnee, riesige Tannen und dichter Schneefall.",
    cost: 2_000_000,
    purchased: false,
    enabled: false,
    type: "world",
    icon: "❄️",
    scene: {
      skyColors: ["#eef7ff", "#a5c8ff"],
      gradientStops: [0, 0.35, 1],
      gradientColors: ["#7aa7e8", "#f4fbff", "#bfdff5"],
      groundColor: "#dbeaf7",
      accentColor: "#ffffff",
      models: ["winter_pines", "winter_snowman"],
      effects: ["winter_snow"],
      lighting: DEFAULT_WORLD_LIGHTING,
    },
  },
  {
    id: "world_moon",
    name: "Auf dem Mond",
    description: "Ein warmer Mondboden mit Kratern und fliegenden Meteoriten.",
    cost: 15_000_000,
    purchased: false,
    enabled: false,
    type: "world",
    icon: "🌕",
    scene: {
      skyColors: ["#fff2c7", "#f0d88f"],
      gradientStops: [0, 0.55, 1],
      gradientColors: ["#040711", "#1c2945", "#7a6330"],
      groundColor: "#f1df9b",
      accentColor: "#ffefb3",
      models: ["moon_craters"],
      effects: ["moon_glow", "moon_meteors"],
      starfield: true,
      lighting: {
        ...DEFAULT_WORLD_LIGHTING,
        moonGlowIntensity: 2,
      },
    },
  },
  {
    id: "world_space",
    name: "Im All",
    description:
      "Ein dunkler Sternenhimmel mit weiter Tiefe und schwächerem Licht.",
    cost: 125_000_000,
    purchased: false,
    enabled: false,
    type: "world",
    icon: "🪐",
    scene: {
      skyColors: ["#03050d", "#11182e"],
      gradientStops: [0, 0.42, 1],
      gradientColors: ["#010208", "#0d1630", "#4d5f87"],
      groundColor: "#07111e",
      accentColor: "#eaf2ff",
      models: ["space_planet", "space_rings"],
      effects: ["space_stars", "space_nebula", "space_dust", "moon_meteors"],
      starfield: true,
      lighting: DEFAULT_WORLD_LIGHTING,
    },
  },
];
